apiVersion: v1
kind: Service
metadata:
  name: birthday-app-service

spec:
  type: NodePort

  selector:
    app: birthday-app

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080